name=ESPWiFiMqttWrapper
version=1.0.6
author=vgorl
category=Communication
maintainer=vgorl
sentence=vgorl's version: ESP8266 and ESP32 WiFi - MQTT Wrapper
paragraph=This library is a wrapper for WiFi and MQTT that serves to make it easier to use.
url=https://github.com/dodo721/ESPWiFiMqttWrapper.git
architectures=esp8266,esp32
depends=PubSubClient

